- functional.lua
This PR adds four functions to `functional` and `tablex`:
In `tablex` it adds:
* `get` - equivalent to `tbl[x]` but allows you to set a context-relevant default.
* `get-in` which is similar, but is for nested tables:
```lua
local get_example = { a = 1, b = 2, c = 3}
print(tablex.get(get_example, "a")) -- => "1"
print(tablex.get(get_example, "b")) -- => "2"
print(tablex.get(get_example, "d")) -- => "nil"
print(tablex.get(get_example, "d", "NOT_FOUND")) -- => "NOT_FOUND"
local get_in_example = {a = {b = {c = {d = "DONE"}}}}
print(tablex.get_in(get_in_example, {"x"}, "NOT_FOUND")) -- => "NOT_FOUND"
print(tablex.get_in(get_in_example, {"a", "b", "d" }, "NOT_FOUND")) -- => "NOT_FOUND"
print(tablex.get_in(get_in_example, {"a", "b", "c", "d"}, "NOT_FOUND")) -- => "DONE" …
```
> Add "group_by" and "remove" to functional

- state_machine.lua
Fixed bug where `start` arg not used in state machine ctor
> Fixed `start` state inclusion in state_machine

- stringx.lua
Checking the _Todo/WIP list_, I saw that the `stringx` table needed some extensions. There are the methods that I've added;
* `ltrim`: similar to trim, but only trims the whitespaces at the left of the string
* `rtrim`: Idem to ltrim, but with the right whitespaces
* `ends_with`: similar to starts_with but it checks that the strings ends with the `posfix` given
> Added some extra methods to stringx

- tablex.lua
Checking the code I noticed there was a "Todo" in the funtion `tablex.insert_sorted` to use binary search instead of linear search on the table to insert an element sortedly.
I have updated `tablex.insert_sorted` to use binary search when the table is sorted(as precondition), otherwise uses the code that was previously in the function(linear search).
I have tested it with this [script](https://gist.github.com/qequ/a110b158a684019e1a8df6b93484e92e), checking leftmost insertion, rightmost insertion and elements in the middle insertion; it has passed all the tests. _I have only tested with the function `less` as <_ (I don't really catch the use of the function less in `tablex.insert_sorted` yet) 
To ensure the sorted table precondition I have added the function `tablex.is_sorted`. It's name …
> Added binary search to tablex.insert_sorted

- tablex.lua
There's a subtle trick in shuffling: you should draw only from the part of the deck you have not seen!  Otherwise, some permutations are more common than others.
> Fix shuffle to avoid bias

- class.lua
when using super_call it failed when the class hierarchie was more complex. i am not an lua expert but from what i understood the code did not call the function in the next higher class but something else (randomly finding the right class if you have a simple design).
i rewrote the code to find the right, next super class that has that very function.
> fix super_call to call in the next higher class

- intersect.lua
- vec2.lua
The separate files should probably be separate PR's (sorry)
For `vec2`, added the functions discussed (feel free to change the names). `major`/`minor` are min/max value component, `farthest`/`closest` are min/max magnitude component. `vec2:minori()` is used in `aabb_point_collide()`.
For `interesect`:
`aabb_point_collide` should be reviewed since it forces the point out if it's exactly on the aabb edge in a hacky-feeling way. Mainly, adding COLLIDE_EPS to the `hs` when calculating the msv direction (line 246)
`aabb_circle_overlap` is standard. However, I did add a helper function that it and collide both use (`aabb_clamp`). Feel free to refactor that out since it's conspicuously the only helper function in `intersect`.
`aabb_circle_collide` generates an msv in a few steps:
1. If circle …
> Added min/max ops to vec2 and aabb_point_collide, aabb_circle_overlap/collide to intersect

- functional.lua
`functional.generate_2d` returns `r`, but the value that should be returned is `result`.
> functional: fix generate_2d return value

- tablex.lua
- Now accepts a table from which it will pick the random value from,
instead of an index
- Changed function name to better reflect the way it now works
> Modified weighted random pick function

- stringx.lua
This pull request introduces an optional amount of times to split the string.
The user may optionally provide a numerical value to tell the function to split up to `max_split` times. If the max is reached, it will then break from the loop and collect the sub-strings as normal. If none is provided, it will behave the same as normal, since `math.huge` would never *actually* be reached.
`math.huge` may not be optimal. I could change it to -1 and instead both check it's not negative one (and thus also less than said non-zero value). However, `math.huge` kinda *just works* here. If there's concern over using it, I'm definitely open to alternatives.
```lua
require("batteries"):export()
local test_value = "zxnzxzxn/gottagofast/weeee/"
-- no max_split
local res = stringx.split(test, "/") …
```
> [Enhancement]: add optional `max_split` to `stringx.split`

- functional.lua
Sometimes I want to map a table functionally via strings, but (as far as I can tell at least) this doesn't exist. I've added it as an alternative function to `map` called `map_index`. It will check if the index is being returned after the value (as long as a value is also returned). If there's no index, it simply maps normally with `table.insert`. Otherwise, the index returned is used.
Alternatively, I could have modified `map` to do this as well, but I wasn't sure if that was the best route. Let me know what you think.
(also apologies for not making this a separate branch, if that is necessary I will fix this)
> functional: add splat

- .github/workflows/luacheck.yml
- .luacheckrc
- assert.lua
- async.lua
- colour.lua
- functional.lua
- intersect.lua
- pretty.lua
- set.lua
- sort.lua
- state_machine.lua
- stringx.lua
- tablex.lua
- vec2.lua
- vec3.lua
Setup a luacheck github action and configuration. Fix some legitimate bugs it discovered.
luacheck is pretty good at finding issues in lua code that a compiler would find in other languages. It has a lot of configuration options to control which warnings it emits. I've ignored a bunch of warnings and then added commits that fix the issues and remove those ignores. There are still a bunch of remaining warnings that are probably fine.
You can run it:
luacheck .
You can see what the action output looks like:
* [Success](https://github.com/idbrii/love-batteries/runs/5411731898?check_suite_focus=true) (commit https://github.com/idbrii/love-batteries/commit/0c193d79019eb2d3fc25e7f0b5aa24197cb8b3ca has a little ✔️ )
* [Failure](https://github.com/idbrii/love-batteries/runs/5411990748?check_suite_ …
> Add luacheck and fix bugs it found

- .github/workflows/testy.yml
- init.lua
- sequence.lua
- tablex.lua
- tests.lua
Remove recursion from second loop of deep_equals. The first loop already checked for equality so the second only needs to check if the keys are there. Add test to validate.
**BREAKING** Implement the comment over copy():
* Replace copy with shallow_copy, deep_copy.
*  These copy functions copy any input type instead of requiring a table. That makes it easier to write generic code where you just want to copy some input without knowing anything about it. Like an event system, save system, etc.
* Replace overlay with shallow_overlay, deep_overlay.
Tests can be run with [testy](https://github.com/siffiejoe/lua-testy) which is a low setup test framework -- it runs local functions prefixed with `test_` and uses `assert` to detect failures.
Add github action to run tests on PR. See test output: …
> tablex: Add deep & shallow for copy, overlay; remove redundant recursion; add tests

- assert.lua
- async.lua
Also reported here: https://github.com/Davidobot/love.js/issues/54.
lovejs crashes love with "attempt to yield across metamethod/C-call boundary" when you try to yield in a coroutine, so we skip wrapping. We lose the coroutine-local callstack, but at least it works.
Also, assert that args is a table and add assert:type_or_nil(). I hit this a couple times when switching from add_timeout() to call().
> async: Skip wrapping with xpcall under lovejs

- uuid.lua
Only contains a function for (the most useful) uuid4 at present.
I'm not sure about the `_global_random` stuff: I took it from `tablex`.
> uuid: added a uuid module

- .test/tests.lua
- stringx.lua
hello. I've added a Title Case function for strings. Haven't run the test case but it looks good 2 me :))
```lua
print(("hello max"):title_case()) -- Hello Max
print(("sphinx of black Quartz, judge My vow"):title_case()) -- Sphinx Of Black Quartz, Judge My Vow
```
> string: add title_case

- assert.lua
This was something I figured would be a nice-to-have while working on something. This asserts that, given a table, `t`, that value `a` is one of the items in the table. If it's not, then it will error. Granted this can be achieved with `functional` and `assert` together, but this allows for it to be done without the need of both modules.
> add `assert:one_of`

- colour.lua
Hi!
As promised, added HSV related functionality.
Please advise. :3
> Add HSV conversion functionality to colour.lua

- state_machine.lua
- vec2.lua
As the title describes, this PR add's meta functions for mathematical operators.
addition:
`vec2(1, 2) + vec2(3, 4)` (4.00, 6.00)
subtraction:
`vec2(1, 2) - vec2(3, 4)` (-2.00, -2.00)
multiplication: 
`vec2(1, 2) * 2`  (2.00, 4.00)
`2 * vec2(3, 4)`  (6.00, 8.00)
`vec2(1, 2) * vec2(3, 4)` (3.00, 8.00)
division:
`vec2(4, 4) / 2`  (2.00, 2.00)
state_machine:
I added another field on the state_machine for the previous state name. This was a really small change and figured I would get input on that too while I'm here, though it probably should have been a separate PR... 
The use-case for me personally was using it to calculate unique behavior based on where we came from. For example I want to enter jump state from wallgrab state, but I want the velocity direction to be slightly tweaked in the …
> vec2: add meta functions for mathematical operators

- state_machine.lua
I just remade the branch
state_machine:
I added another field on the state_machine for the previous state name.
The use-case for me personally was using it to calculate unique behavior based on where we came from. For example I want to enter jump state from wallgrab state, but I want the velocity direction to be slightly tweaked in the jump state's update method if we came from wallgrab.
Let me know your thoughts!
> state_machine: include prev_state_name

- mathx.lua
Taken from [lume](https://github.com/rxi/lume/blob/master/lume.lua#L111).
Old:
```lua
print(mathx.pingpong(100)) -- -198
print(mathx.pingpong(101)) -- -200
```
New:
```lua
print(mathx.pingpong(100)) -- 0
print(mathx.pingpong(101)) -- 1
```
> Fix incorrect implementation of pingpong
